name: Build Status
on: [push, pull_request, workflow_dispatch]

env:
    CARGO_TERM_COLOR: always
    CI: false

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          ui/main-window/node_modules
          ui/stdout/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('ui/main-window/package-lock.json', 'ui/main-window/yarn.lock', 'ui/stdout/package-lock.json', 'ui/stdout/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Cargo tools
      run: |
          cargo install cargo-bundle
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "rust" 
    - name: Build Application
      run: |
        make setup && make release
    - name: Bundle Application
      run: |
          cargo bundle --format osx --release
    - name: Archive Application
      uses: actions/upload-artifact@v4
      with:
        name: Conductor.app
        path: target/release/bundle/osx/
